import type { Metadata } from "next";
import { Sora, DM_Sans } from "next/font/google";
import localFont from 'next/font/local';
import "./globals.css";
import ChatBotPopoverComponent from "./components/chatbot-popover";
import WhatsAppPopoverComponent from "./components/whatsapp-popover";

export const playwrite = localFont({
  src: '../../public/Fonts/static/PlaywriteRO-Regular.ttf',
  variable: '--font-playwrite'
});

const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sora.variable} ${dmSans.variable} ${playwrite.variable} antialiased`}>
        {children}
        <ChatBotPopoverComponent />
        <WhatsAppPopoverComponent />
      </body>
    </html>
  );
}